# Generated by Django 5.2.8 on 2025-11-18 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopConsumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('bandwidth', models.FloatField()),
                ('percentage', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-bandwidth'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('message', models.TextField()),
                ('value', models.FloatField()),
                ('threshold', models.FloatField()),
                ('ai_analysis', models.TextField(blank=True, null=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('affected_users', models.IntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'severity'], name='monitoring__created_acc85d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('network', 'Network'), ('server', 'Server'), ('firewall', 'Firewall')], db_index=True, max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(max_length=100)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'metric_type'], name='monitoring__timesta_cc7bb0_idx')],
            },
        ),
    ]
